{% set name = "lhcbstyle" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lhcbstyle-{{ version }}.tar.gz
  sha256: 8e385afb6eb8afea177e6801d334cc855e774983cba48d9c1135a3fda96ead2d

build:
  number: 0
  noarch: python
  # lhcbstyle doesn't link to ROOT so there is no need to constrain the runtime version
  ignore_run_exports:
    - root_base
  entry_points:
    - lhcbstyle = lhcbstyle.__main__:parse_args
  script:
    - {{ PYTHON }} -m pip install . -vv
    - lhcbstyle install

requirements:
  host:
    - pip
    - python >=3.7
    - root_base
  run:
    - python >=3.7
    - root_base

test:
  imports:
    - lhcbstyle
  commands:
    - pip check
    - lhcbstyle --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-docs/lhcbstyle
  summary: LHCb style for ROOT plots
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - admorris
    - chrisburr
